worker_processes 1;
events { worker_connections 1024; }
http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  upstream ingest { server ingest-service:8000; }
  upstream simulator { server simulator-service:8000; }
  upstream diagnosis { server diagnosis-service:8000; }
  upstream policy { server policy-service:8000; }
  upstream executor { server executor-service:8000; }

  server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /health {
      default_type application/json;
      return 200 '{"ok":true,"edge":"nginx"}';
    }

    location /api/ingest/ {
      proxy_pass http://ingest/;
    }
    location /api/simulator/ {
      proxy_pass http://simulator/;
    }
    location /api/diagnosis/ {
      proxy_pass http://diagnosis/;
    }
    location /api/policy/ {
      proxy_pass http://policy/;
    }
    location /api/executor/ {
      proxy_pass http://executor/;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
